buildConfiguration:
  buildCommand: npm run build
  installDependenciesStep:
    command: npm install
    requiredFiles:
      - package.json
      - package-lock.json
      - .npmrc
livePreviewConfiguration:
  setupCommand: ":"
# Authentication can be setup here. First, follow the instructions to create
# the authentication policy via the admin console and then specify the policy
# name here.
authentication:
  policyName: test-yext-auth